name: deploy 
on: 
  push

permissions:
  contents: write

jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Node setup 
        uses: actions/setup-node@v4 
        with: 
          node-version: '22'

      - name: Deploy 
        run: | 
          npm install 
          npm run build 
          npm run deploy > deploy.log 
          DEPLOY_URL=$(grep -o 'https://[a-zA-Z0-9.-]*\.pages\.dev' deploy.log) 
          echo "Deployment URL: $DEPLOY_URL" 
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"homepage": "$DEPLOY_URL"}' \
            https://api.github.com/repos/${{ github.repository }}
          
        env: 
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
