name: deploy 
on: 
  push:
    branches: 
      - main

permissions:
  contents: write

jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Node setup 
        uses: actions/setup-node@v4 
        with: 
          node-version: '22'

      - name: Deploy 
        run: | 
          npm install 
          npm run build 
          npm run deploy
        env: 
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          