name: deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Deploy
        run: |
          npm install
          npm run build
          npm run deploy > deploy.log
          DEPLOY_URL=$(grep -o 'https://[a-zA-Z0-9.-]*\.pages\.dev' deploy.log)
          echo "Deployment URL: $DEPLOY_URL"
          if [ -n "$DEPLOY_URL" ]; then
            if grep -q '### Deployment URL' README.md; then
              sed -i "s|^.*https://.*pages.dev.*$|$DEPLOY_URL|" README.md
            else
              echo -e "\n### Deployment URL\n$DEPLOY_URL" >> README.md
            fi
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Create Pull Request
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git checkout -b update-deployment-url
          git add README.md
          git commit -m "[bot] update deployment URL in README"
          git push --set-upstream origin update-deployment-url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pull Request using GitHub CLI
        run: |
          gh pr create --title "Update deployment URL" --body "Update the deployment URL in the README." --base main --head update-deployment-url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: |
          # Ensure that the PR is merged automatically once it passes checks
          gh pr merge --merge --auto --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
